services:
  calendario:
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-andpra70/calendario}:${TAG:-latest}"
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6065:80"
